filebeat.autodiscover:
  providers:
  - type: docker
    templates:
    - condition:
        contains:
          docker.container.image: "httpd"
      config:
      - module: apache2
        access:
          prospector:
            type: docker
            containers.ids:
            - "${data.docker.container.id}"

processors:
- add_docker_metadata: ~

setup.kibana:
  host: "kibana:5601"

output.logstash:
  hosts: ["logstash:5044"]

output.console:
  pretty: true
  enabled: false



