setup.kibana:
  host: "kibana:5601"

output.logstash:
  hosts: ["logstash:5044"]

filebeat.modules:
- module: kafka

#filebeat.inputs:
#- type: docker
#  containers:
#    path: "/var/lib/docker/containers"
#    stream: "all"
#    ids:
#      - '*'

filebeat.autodiscover:
  providers:
  - type: docker
    templates:
    - condition:
        contains:
          docker.container.image: confluent
      config:
      - module: kafka
        log:
          enabled: true
    - condition:
        contains:
          docker.container.image: confluent
      config:
      - type: docker
        containers.ids:
        - "${data.docker.container.id}"

output.console:
  pretty: true
  enabled: false





